project:
  type: book

book:
  title: "Black Rock City Census 2024 Population Report"
  author: "Aaron \"Murrs\" Shev"
  date: "2/17/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - sociodemo.qmd
    - regionals_media_volunteering.qmd
    - perspectives.qmd
    - travel.qmd
    - camp_logistics.qmd
    - acknowledgments.qmd
    - references.qmd
  cover-image: Logo.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

