# Contributions and acknowledgments {.unnumbered}

**Black Rock City Census Manager:** Maher Abdel-Sattar (Random) PharmD, MS, FAMCP

**Principal Investigator:** Samuel Ehrenreich, Ph.D.

**Study Design:** Aaron Shev (Murrs), Ph.D.; Dominic Beaulieu-Prévost (Hunter), Ph.D 

**Data Analysis, and Visualization:** Aaron Shev (Murrs), Ph.D.; Matt Dunford; Stephanie May; Dusty Nuts, Ph.D.; Rachel McKay (Chipper); Christina Ancira

**Special thanks and acknowledgements:**

-   The more than 150 volunteers of the 2024 Census Lab including: research collaborators, volunteer coordinators, camp builders, random samplers, key punchers, Census Lab hosts, graphic designers, and many more!

-   Special thanks to Dana DeVaul (DV8) whose work on the 2018 population report was the basis for many elements in this report, and to Dominic Beaulieu-Prévost (Hunter) for cleaning and weighting data from 2013 to 2019.

-   We would also like to thank Dominique DeBucquoy Dodley (Great Question), Leslie Moyer, Kristy Nuehouse (Brinkley), Carly Rhodes (Hi-Chew), and the Burning Man Communications Department.

-   Additionally, our thanks to Burning Man Project for the resources they provide both on playa and off playa and for supporting the Black Rock City Census!

-   Finally, we would like to extend our sincere thanks to all of the Burning Man participants who have taken the time to provide their data. This project would not exist without our respondents.

## For more information {.unnumbered}

To contact the Census Lab, email census\@burningman.org

Hive: [Census Community on Hive](https://hive.burningman.org/spaces/14264554/content?_gl=1*1o7894l*_ga*MTQ3MDgxMjExNy4xNzA5NzgwNTQ3*_ga_FWW1ZLL84X*czE3NTE3NzczNzUkbzgxJGcwJHQxNzUxNzc3Mzc1JGo2MCRsMCRoMA..*_ga_411YJ8ZFDE*czE3NTE3NzczNzUkbzEzNCRnMCR0MTc1MTc3NzM3NSRqNjAkbDAkaDA.*_ga_4334FXWCMM*czE3NTE3NzczNzUkbzEwOSRnMCR0MTc1MTc3NzM3NSRqNjAkbDAkaDA.){.uri}

Census Lab Blog: <https://journal.burningman.org/author/census/>

Census Lab Data Archive: <https://burningman.org/culture/history/brc-history/census-data/>

Citation: Shev, A.B., Dunford, M., May, S., Beaulieu-Prévost, D., Abdel-Sattar M., and the 2024 Census Lab. (2025). Black Rock City Census: 2013-2024 Population Analysis. Black Rock City Census.

Copyright © 2025 Shev et al.
